name: pokedex_manha
description: A new Flutter project.


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  dartz: ^0.9.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: PokeGoTypes
      fonts:
        - asset: lib/assets/fonts/PokeGOTypes.ttf
        
    - family: Pokemon
      fonts:
        - asset: lib/assets/fonts/PokemonSolid.ttf